### PR TITLE
Do not set VotableManager as the default manager

### PR DESCRIPTION
**Pull request by phala**
Hi @jamesturk. Can you also have a look at this one please?
Setting the `VotableManager` as the default here causes some undesirable effects in the models that use it. More info on this can be found [in the docs](https://docs.djangoproject.com/en/1.11/topics/db/managers/#default-managers)

If you're happy with this, can you also prepare a release?

### CODE REVIEW

**Comment by jamesturk** [comment]
if I'm understanding correctly this would be a pretty significant breaking change, no?

**Comment by phala** [comment]
hi@jamesturk, I am using Django 1.11, the problem I am experiencing relates to when voting is enabled in a parent class. Having `VotableManager` as the default caused problems in my case where some django signals where not being emitted.

Having read the docs, I thought it might be best to let the `default_manager` be specified explicitly on the model. Could not having the `VotableManager` as default cause problems I am unaware of?

**Comment by jamesturk** [comment]
I'll need to take a closer look at this, I figured it'd affect people that
were using it as Model.objects.all() and then expecting the vote fields,
but I'm running around this morning and probably not thinking about this
right.  I'll try to find some more time soon to familiarize myself with the
issue

**Comment by phala** [comment]
Hi @jamesturk. Have you had a chance to look into this?

**Comment by phala** [comment]
Hi @jamesturk. Have you had a chance to look into this?

**Comment by jamesturk** [comment]
I haven't, do you know how this affects backwards compability?  I haven't
had time to research this

**Comment by phala** [comment]
@jamesturk this shouldn't affect backwards compatibility since the feature is new in Django 1.10 as detailed [in the docs](https://docs.djangoproject.com/en/1.11/ref/models/options/#default-manager-name)

**Comment by jamesturk** [comment]
Can you provide a test for the broken behavior?  It seems like if people were relying on this being the default manager this is going to be backwards compatible, but if we can identify what is fixing that'd potentially make this worthwhile

**Comment by phala** [comment]
@jamesturk please have a look and consider the tests I have added.
Not setting the default manager does not affect any functionality.
I do still think that having a 3rd party lib is not best practise. Shouldn't an app author set a default manager explicitly on said model?

In the tests, `secretballot.enable_voting_on(Link)` sets the manager's name as `"objects"` where for the `AnotherLink` model, a custom manager name is used.
```
secretballot.enable_voting_on(AnotherLink,
                              manager_name='ballot_custom_manager'
                              )
```

It is enough to provide a name for the `manager` or rely on the default, which is `objects`.
The ability to do `Link.objects.get().vote_total` comes from this, and not from setting the default manager.

I hope my tests illustrate that removing the default_manager declaration does not affect current functionality.

**Comment by jamesturk** [comment]
thanks, makes sense to me 👍

**Comment by phala** [comment]
@jamesturk looking forward to the next release :1st_place_medal:

**Pull request merged**
