### PR TITLE
fix #55

### LINKED ISSUE #55: ValueError: invalid literal for int() with base 10
I suppose `django-secretballot` is not adapted to string IDs

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
@jamesturk any chance to see this changes applied and released on pypi? we are using `secretballot` in production

**Comment by jamesturk** [comment]
this is a backwards incompatible change, but I'd be open to it in theory

can you include a migration?

**Comment by bashu** [comment]
see https://github.com/django/django-contrib-comments/blob/master/django_comments/abstracts.py#L29 how it should be done

**Comment by bashu** [comment]
hey @jamesturk  we use your wonderful app at https://altacucina.co, and it would be awesome if you can release a version that address this issue

**Comment by bashu** [comment]
> can you include a migration?
fixed

**Comment by bashu** [comment]
@jamesturk ?

**Comment by jamesturk** [comment]
No plans yet, I'll need to consider an approach to releasing this since it
breaks backwards incompatibility (you can use your own fork in the meantime
hopefully :))

**Pull request closed without merging**
